### ISSUE TITLE
Fails to Compile on FreeBSD-14.3

### ISSUE THREAD

**Issue by WildOne69** [hharte/mm_manager#26]
I'm trying to compile this on FreeBSD 14.3-RELEASE-p1, and it's failing to compile. Could somebody help me get it to compile, please?

cmake . completes with no errors

:/home/rusty/mm_manager # make
[  2%] Built target mm_util
[  5%] Built target sqlite3
[  8%] Built target mm_serial
[  9%] Building C object CMakeFiles/mm_manager.dir/src/mm_udp.c.o
/home/rusty/mm_manager/src/mm_udp.c:41:45: error: use of undeclared identifier 'IPPROTO_UDP'
   41 |     if ((sock = socket(AF_INET, SOCK_DGRAM, IPPROTO_UDP)) == INVALID_SOCKET)
      |                                             ^
/home/rusty/mm_manager/src/mm_udp.c:52:39: error: invalid application of 'sizeof' to an incomplete type 'struct sockaddr_in'
   52 |     memset((char *) &si_src, 0, sizeof(si_src));
      |                                       ^~~~~~~~
/home/rusty/mm_manager/src/mm_udp.c:27:8: note: forward declaration of 'struct sockaddr_in'
   27 | struct sockaddr_in si_src, si_dst;
      |        ^
/home/rusty/mm_manager/src/mm_udp.c:53:11: error: incomplete definition of type 'struct sockaddr_in'
   53 |     si_src.sin_family = AF_INET;
      |     ~~~~~~^
/home/rusty/mm_manager/src/mm_udp.c:27:8: note: forward declaration of 'struct sockaddr_in'
   27 | struct sockaddr_in si_src, si_dst;
      |        ^
/home/rusty/mm_manager/src/mm_udp.c:54:11: error: incomplete definition of type 'struct sockaddr_in'
   54 |     si_src.sin_port = htons(port);
      |     ~~~~~~^
/home/rusty/mm_manager/src/mm_udp.c:27:8: note: forward declaration of 'struct sockaddr_in'
   27 | struct sockaddr_in si_src, si_dst;
      |        ^
/home/rusty/mm_manager/src/mm_udp.c:55:11: error: incomplete definition of type 'struct sockaddr_in'
   55 |     si_src.sin_addr.s_addr = INADDR_ANY;
      |     ~~~~~~^
/home/rusty/mm_manager/src/mm_udp.c:27:8: note: forward declaration of 'struct sockaddr_in'
   27 | struct sockaddr_in si_src, si_dst;
      |        ^
/home/rusty/mm_manager/src/mm_udp.c:55:30: error: use of undeclared identifier 'INADDR_ANY'
   55 |     si_src.sin_addr.s_addr = INADDR_ANY;
      |                              ^
/home/rusty/mm_manager/src/mm_udp.c:57:39: error: invalid application of 'sizeof' to an incomplete type 'struct sockaddr_in'
   57 |     memset((char *) &si_dst, 0, sizeof(si_dst));
      |                                       ^~~~~~~~
/home/rusty/mm_manager/src/mm_udp.c:27:8: note: forward declaration of 'struct sockaddr_in'
   27 | struct sockaddr_in si_src, si_dst;
      |        ^
/home/rusty/mm_manager/src/mm_udp.c:58:11: error: incomplete definition of type 'struct sockaddr_in'
   58 |     si_dst.sin_family = AF_INET;
      |     ~~~~~~^
/home/rusty/mm_manager/src/mm_udp.c:27:8: note: forward declaration of 'struct sockaddr_in'
   27 | struct sockaddr_in si_src, si_dst;
      |        ^
/home/rusty/mm_manager/src/mm_udp.c:59:11: error: incomplete definition of type 'struct sockaddr_in'
   59 |     si_dst.sin_port = htons(port);
      |     ~~~~~~^
/home/rusty/mm_manager/src/mm_udp.c:27:8: note: forward declaration of 'struct sockaddr_in'
   27 | struct sockaddr_in si_src, si_dst;
      |        ^
/home/rusty/mm_manager/src/mm_udp.c:60:11: error: incomplete definition of type 'struct sockaddr_in'
   60 |     si_dst.sin_addr.s_addr = inet_addr(ip_addr);
      |     ~~~~~~^
/home/rusty/mm_manager/src/mm_udp.c:27:8: note: forward declaration of 'struct sockaddr_in'
   27 | struct sockaddr_in si_src, si_dst;
      |        ^
/home/rusty/mm_manager/src/mm_udp.c:63:54: error: invalid application of 'sizeof' to an incomplete type 'struct sockaddr_in'
   63 |     if( bind(sock , (struct sockaddr*)&si_src, sizeof(si_src) ) == SOCKET_ERROR)
      |                                                      ^~~~~~~~
/home/rusty/mm_manager/src/mm_udp.c:27:8: note: forward declaration of 'struct sockaddr_in'
   27 | struct sockaddr_in si_src, si_dst;
      |        ^
/home/rusty/mm_manager/src/mm_udp.c:81:119: error: invalid application of 'sizeof' to an incomplete type 'struct sockaddr_in'
   81 |     if (sendto(sock, (const char *)&pkt->hdr.start, (size_t)pkt->hdr.pktlen + 1, 0, (struct sockaddr *)&si_dst, sizeof(si_dst)) == SOCKET_ERROR)
      |                                                                                                                       ^~~~~~~~
/home/rusty/mm_manager/src/mm_udp.c:27:8: note: forward declaration of 'struct sockaddr_in'
   27 | struct sockaddr_in si_src, si_dst;
      |        ^
/home/rusty/mm_manager/src/mm_udp.c:27:20: error: tentative definition has type 'struct sockaddr_in' that is never completed
   27 | struct sockaddr_in si_src, si_dst;
      |                    ^
/home/rusty/mm_manager/src/mm_udp.c:27:8: note: forward declaration of 'struct sockaddr_in'
   27 | struct sockaddr_in si_src, si_dst;
      |        ^
/home/rusty/mm_manager/src/mm_udp.c:27:28: error: tentative definition has type 'struct sockaddr_in' that is never completed
   27 | struct sockaddr_in si_src, si_dst;
      |                            ^
/home/rusty/mm_manager/src/mm_udp.c:27:8: note: forward declaration of 'struct sockaddr_in'
   27 | struct sockaddr_in si_src, si_dst;
      |        ^
14 errors generated.
*** Error code 1

**Comment by hharte** [comment]
Hello,

Thank you for the bug report.  This issue should be fixed via 60b27f1.  With this change, I was able to compile on FreeBSD 14.3-RELEASE releng/14.3-n271432-8c9ce319fef7 GENERIC amd64.  Please let me know how mm_manager works on FreeBSD.  I have not tried it there before.

Thanks,
Howard
